### ISSUE TITLE
Issues with my website not being online 

### ISSUE THREAD

**Issue by lmiin-tu81** [lmiin-tu81/css-validation-fixes#1]
@hellachella @raven-rhea 
Markbot keeps saying that my website is not online and I have tried recloning the repository and working on it again.

**Comment by raven-rhea** [comment]
YOur index.html file is capitalized

**Comment by lmiin-tu81** [comment]
The index file on my laptop is named properly but the one on GitHub app and website is still capitalized. I have tried deleting the index file and pasting the content into a new properly named index file but the new file still appears on Github as Index.html. I have also tried closing and re-opening the Github app and also renaming the index file in Finders.

**Comment by lmiin-tu81** [comment]
Nevermind, I was able to fix it.
